@startuml class_diagram

class Subito {
    - __url: str
    get_insertion(url: str) -> dict
    get_query_page(query: str, page: int) -> list[dict]
    get_query(query: str) -> list[dict]
}

class SubitoGetter {
    - __url: str
    get_insertion(url: str) -> dict
    get_insertions(url: str) -> list[dict]
}

class SubitoExtractor {
    - __insertion_extractor: selectorlib.Extractor
    - __insertions_extractor: selectorlib.Extractor
    extract_insertion(response: str) -> dict
    extract_insertions(response: str) -> list[dict]
}

Subito --> SubitoGetter
Subito --> SubitoExtractor

@enduml
